#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")/../.."
shopt -s extglob

archive_match="coop(-[a-zA-Z0-9]+)?-linux-$(uname -m)\.tar\.gz"
archive=$(ls "target/release" | grep -E ${archive_match})

export ARCHIVE="$archive"
export APP_ID="su.reya.coop"
export APP_NAME="Coop"
export BRANDING_LIGHT="#FFE629"
export BRANDING_DARK="#FFE629"
export ICON_FILE="icon"
export CHANNEL="stable"

envsubst < "crates/coop/resources/flatpak/manifest-template.json" > "$APP_ID.json"
flatpak-builder --user --install --force-clean build "$APP_ID.json"
flatpak build-bundle ~/.local/share/flatpak/repo "target/release/$APP_ID.flatpak" "$APP_ID"
echo "Created 'target/release/$APP_ID.flatpak'"
