array_width = 80
max_width = 120
tab_spaces = 4
newline_style = "Auto"
reorder_imports = true
reorder_modules = true
indent_style = "Block"
normalize_comments = false
imports_granularity = "Module"
group_imports = "StdExternalCrate"
