/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AccountChatsIdImport } from './routes/$account.chats.$id'

// Create Virtual Routes

const NostrConnectLazyImport = createFileRoute('/nostr-connect')()
const NewLazyImport = createFileRoute('/new')()
const ImportKeyLazyImport = createFileRoute('/import-key')()
const CreateAccountLazyImport = createFileRoute('/create-account')()
const AccountChatsLazyImport = createFileRoute('/$account/chats')()
const AccountChatsNewLazyImport = createFileRoute('/$account/chats/new')()

// Create/Update Routes

const NostrConnectLazyRoute = NostrConnectLazyImport.update({
  path: '/nostr-connect',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/nostr-connect.lazy').then((d) => d.Route))

const NewLazyRoute = NewLazyImport.update({
  path: '/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/new.lazy').then((d) => d.Route))

const ImportKeyLazyRoute = ImportKeyLazyImport.update({
  path: '/import-key',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/import-key.lazy').then((d) => d.Route))

const CreateAccountLazyRoute = CreateAccountLazyImport.update({
  path: '/create-account',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create-account.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccountChatsLazyRoute = AccountChatsLazyImport.update({
  path: '/$account/chats',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$account.chats.lazy').then((d) => d.Route),
)

const AccountChatsNewLazyRoute = AccountChatsNewLazyImport.update({
  path: '/new',
  getParentRoute: () => AccountChatsLazyRoute,
} as any).lazy(() =>
  import('./routes/$account.chats.new.lazy').then((d) => d.Route),
)

const AccountChatsIdRoute = AccountChatsIdImport.update({
  path: '/$id',
  getParentRoute: () => AccountChatsLazyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountLazyImport
      parentRoute: typeof rootRoute
    }
    '/import-key': {
      id: '/import-key'
      path: '/import-key'
      fullPath: '/import-key'
      preLoaderRoute: typeof ImportKeyLazyImport
      parentRoute: typeof rootRoute
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewLazyImport
      parentRoute: typeof rootRoute
    }
    '/nostr-connect': {
      id: '/nostr-connect'
      path: '/nostr-connect'
      fullPath: '/nostr-connect'
      preLoaderRoute: typeof NostrConnectLazyImport
      parentRoute: typeof rootRoute
    }
    '/$account/chats': {
      id: '/$account/chats'
      path: '/$account/chats'
      fullPath: '/$account/chats'
      preLoaderRoute: typeof AccountChatsLazyImport
      parentRoute: typeof rootRoute
    }
    '/$account/chats/$id': {
      id: '/$account/chats/$id'
      path: '/$id'
      fullPath: '/$account/chats/$id'
      preLoaderRoute: typeof AccountChatsIdImport
      parentRoute: typeof AccountChatsLazyImport
    }
    '/$account/chats/new': {
      id: '/$account/chats/new'
      path: '/new'
      fullPath: '/$account/chats/new'
      preLoaderRoute: typeof AccountChatsNewLazyImport
      parentRoute: typeof AccountChatsLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CreateAccountLazyRoute,
  ImportKeyLazyRoute,
  NewLazyRoute,
  NostrConnectLazyRoute,
  AccountChatsLazyRoute: AccountChatsLazyRoute.addChildren({
    AccountChatsIdRoute,
    AccountChatsNewLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-account",
        "/import-key",
        "/new",
        "/nostr-connect",
        "/$account/chats"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-account": {
      "filePath": "create-account.lazy.tsx"
    },
    "/import-key": {
      "filePath": "import-key.lazy.tsx"
    },
    "/new": {
      "filePath": "new.lazy.tsx"
    },
    "/nostr-connect": {
      "filePath": "nostr-connect.lazy.tsx"
    },
    "/$account/chats": {
      "filePath": "$account.chats.lazy.tsx",
      "children": [
        "/$account/chats/$id",
        "/$account/chats/new"
      ]
    },
    "/$account/chats/$id": {
      "filePath": "$account.chats.$id.tsx",
      "parent": "/$account/chats"
    },
    "/$account/chats/new": {
      "filePath": "$account.chats.new.lazy.tsx",
      "parent": "/$account/chats"
    }
  }
}
ROUTE_MANIFEST_END */
